import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar, { NavbarAuthenticated } from "@/components/Navbar";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./(auth)/api/auth/[...nextauth]/route";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "min-h-screen pt-16 antialiased light bg-background text-foreground"
        )}
      >
        <Navbar />
        <div className="container max-w-7xl mx-auto h-full pt-12 antialiased mb-16">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
